### ISSUE TITLE
Delete Data

### ISSUE THREAD

**Issue by ICRI-Cities** [enableiot/iotkit-api#4]
There doesnt seem to be anyway to delete datapoints from enableiot.com. My device threw out some junk data before I was able to patch it and now I have a few junk data points in the component. I know I can delete the component and re-add the good data but thats quite a process to remove a few bad data points. Is there a way to remove just a few data points from a component?

**Comment by adrianweber** [comment]
Unfortunately there is no API for removing data points from a component. As you wrote, You have to re-add the whole component in order to erase data.
